### ISSUE TITLE
Bug in theno day/ variational_MRF

### ISSUE THREAD

**Issue by finmod** [SheffieldML/notebook#7]
Running with this configuration:
Software	Version
Python	3.5.0 64bit [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
IPython	4.0.0
OS	Linux 3.19.0 33 generic x86_64 with debian jessie sid
numpy	1.10.1
scipy	0.16.0
matplotlib	1.5.0
theano	0.7.0
GPy	0.8.31
Sat Nov 21 14:42:17 2015 CET

The following error occurs in ln [5], ln [8] to do with 64 bit architecture and ln [9] to do with python 3 for urllib
-------------------------------------------
In [5]:

f(Xval, Yval, b_init, h_init, e_init)
f(Xval, Yval, b_init, h_init, e_init)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-450bd3c8efec> in <module>()
----> 1 f(Xval, Yval, b_init, h_init, e_init)

/home/denis/anaconda3/lib/python3.5/site-packages/theano/compile/function_module.py in __call__(self, *args, **kwargs)
    511                     try:
    512                         s.storage[0] = s.type.filter(arg, strict=s.strict,
--> 513                                 allow_downcast=s.allow_downcast)
    514 
    515                     except Exception as e:

/home/denis/anaconda3/lib/python3.5/site-packages/theano/tensor/type.py in filter(self, data, strict, allow_downcast)
    129                             '"function".'
    130                             % (self, data.dtype, self.dtype))
--> 131                         raise TypeError(err_msg, data)
    132                 elif (allow_downcast is None and
    133                         type(data) is float and

TypeError: ('Bad input argument to theano function at index 0(0-based)', 'TensorType(int32, matrix) cannot store a value of dtype int64 without risking loss of precision. If you do not mind this loss, you can: 1) explicitly cast your data to int32, or 2) set "allow_input_downcast=True" when calling "function".', array([[ 1, -1, -1,  1, -1],
       [ 1,  1,  1,  1,  1],
       [-1,  1,  1, -1,  1],
       [ 1, -1, -1, -1,  1],
       [ 1,  1,  1,  1,  1],
       [-1,  1, -1, -1,  1],
       [-1,  1,  1,  1, -1],
       [-1, -1, -1, -1,  1],
       [ 1, -1, -1,  1,  1],
       [-1, -1, -1, -1,  1]]))

------------------------------------
In In [8]:

Ef(RSval.flatten(), Yval, b_init, h_init, e_init, N, D)
​
options = dict()
options['disp']=True
​
res=sp.optimize.minimize(Ef, RSval.flatten(), (Yval, b_init, h_init, e_init, N, D), jac=True, options=options)#, bounds=optBounds)
​
optimised_params = res['x']
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-8-cbc2016e3df9> in <module>()
----> 1 Ef(RSval.flatten(), Yval, b_init, h_init, e_init, N, D)
      2 
      3 options = dict()
      4 options['disp']=True
      5 

/home/denis/anaconda3/lib/python3.5/site-packages/theano/compile/function_module.py in __call__(self, *args, **kwargs)
    511                     try:
    512                         s.storage[0] = s.type.filter(arg, strict=s.strict,
--> 513                                 allow_downcast=s.allow_downcast)
    514 
    515                     except Exception as e:

/home/denis/anaconda3/lib/python3.5/site-packages/theano/tensor/type.py in filter(self, data, strict, allow_downcast)
    129                             '"function".'
    130                             % (self, data.dtype, self.dtype))
--> 131                         raise TypeError(err_msg, data)
    132                 elif (allow_downcast is None and
    133                         type(data) is float and

TypeError: ('Bad input argument to theano function at index 1(0-based)', 'TensorType(int32, matrix) cannot store a value of dtype int64 without risking loss of precision. If you do not mind this loss, you can: 1) explicitly cast your data to int32, or 2) set "allow_input_downcast=True" when calling "function".', array([[ 1, -1, -1,  1,  1],
       [-1, -1, -1, -1,  1],
       [-1,  1,  1,  1,  1],
       [ 1, -1,  1, -1, -1],
       [ 1, -1, -1,  1,  1],
       [ 1,  1, -1,  1,  1],
       [ 1,  1, -1,  1,  1],
       [-1,  1,  1,  1, -1],
       [ 1, -1,  1, -1, -1],
       [-1,  1, -1,  1, -1]]))

-------------------------------
In [9]:

#import urllib, cStringIO
#URL='http://upload.wikimedia.org/wikipedia/en/thumb/9/9e/Flag_of_Japan.svg/1280px-Flag_of_Japan.svg.png'
#file = cStringIO.StringIO(urllib.urlopen(URL).read())
#img = Image.open(file).convert('L')
​
import urllib.request, urllib.parse, urllib.error, io
URL='http://upload.wikimedia.org/wikipedia/en/thumb/9/9e/Flag_of_Japan.svg/1280px-Flag_of_Japan.svg.png'
file = io.StringIO(urllib.request.urlopen(URL).read())
img = Image.open(file).convert('L')
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-9-8a6dc9cbd331> in <module>()
      6 import urllib.request, urllib.parse, urllib.error, io
      7 URL='http://upload.wikimedia.org/wikipedia/en/thumb/9/9e/Flag_of_Japan.svg/1280px-Flag_of_Japan.svg.png'
----> 8 file = io.StringIO(urllib.request.urlopen(URL).read())
      9 img = Image.open(file).convert('L')

TypeError: initial_value must be str or None, not bytes

**Comment by mzwiessele** [comment]
These are old notebooks, which are there as information of what was done. These will not be fixed in the future.
